# Generated by Django 5.0 on 2026-07-27 11:51

import django.db.models.deletion
import proposals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("needs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان پیشنهاد"),
                ),
                ("technical_description", models.TextField(verbose_name="شرح فنی")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="قیمت (تومان)"
                    ),
                ),
                (
                    "delivery_time",
                    models.CharField(max_length=100, verbose_name="زمان تحویل"),
                ),
                ("terms", models.TextField(blank=True, verbose_name="شرایط و ضوابط")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="فرمت\u200cهای مجاز: .docx, .pdf, .tex",
                        null=True,
                        upload_to=proposals.models.proposal_file_path,
                        verbose_name="فایل پروپوزال",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("sent", "ارسال شده"),
                            ("under_review", "در حال بررسی"),
                            ("accepted", "پذیرفته شده"),
                            ("rejected", "رد شده"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "need",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="needs.need",
                        verbose_name="نیاز",
                    ),
                ),
            ],
            options={
                "verbose_name": "پروپوزال",
                "verbose_name_plural": "پروپوزال\u200cها",
                "ordering": ["-created_at"],
            },
        ),
    ]
