# Generated by Django 5.0 on 2026-08-21 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_initial'),
        ('proposals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='products.supply', verbose_name='عرضه'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['need', 'status'], name='proposals_p_need_id_068164_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['sender'], name='proposals_p_sender__e0d40e_idx'),
        ),
    ]
