# Generated by Django 5.0 on 2026-08-21 10:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', ckeditor.fields.RichTextField(verbose_name='شرایط قرارداد')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ قرارداد')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس قرارداد'), ('legal_review', 'بررسی حقوقی'), ('valuation', 'ارزش\u200cگذاری'), ('approved_buyer', 'تأیید خریدار'), ('approved_supplier', 'تأیید فروشنده'), ('signed', 'امضا شده'), ('execution', 'در حال اجرا'), ('completed', 'تکمیل شده'), ('disputed', 'وارد اختلاف شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='فایل قرارداد')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ امضا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قرارداد',
                'verbose_name_plural': 'قراردادها',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان فاز')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید')),
                ('status', models.CharField(choices=[('not_started', 'شروع نشده'), ('in_progress', 'در حال انجام'), ('awaiting_approval', 'در انتظار تأیید'), ('needs_revision', 'نیازمند اصلاح'), ('completed', 'تکمیل شده')], default='not_started', max_length=20, verbose_name='وضعیت')),
                ('deliverables', models.FileField(blank=True, null=True, upload_to='deliverables/', verbose_name='خروجی\u200cها')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
            ],
            options={
                'verbose_name': 'نقطه عطف',
                'verbose_name_plural': 'نقاط عطف',
            },
        ),
    ]
