# Generated by Django 5.0 on 2026-08-21 10:52

import ckeditor.fields
import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('supply_type', models.CharField(choices=[('product', 'محصول'), ('service', 'خدمت')], default='product', max_length=20, verbose_name='نوع عرضه')),
                ('category', models.CharField(max_length=100, verbose_name='دسته\u200cبندی')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='صنعت')),
                ('technology', models.CharField(blank=True, max_length=100, verbose_name='فناوری')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='شهر')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('quantity', models.CharField(max_length=50, verbose_name='مقدار')),
                ('unit', models.CharField(max_length=50, verbose_name='واحد')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='قیمت (تومان)')),
                ('trl', models.CharField(blank=True, max_length=10, verbose_name='سطح آمادگی فناوری')),
                ('documents', models.JSONField(blank=True, default=list, verbose_name='مستندات')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('draft', 'پیش\u200cنویس'), ('submitted', 'ارسال برای بررسی'), ('evaluating', 'در حال ارزیابی'), ('needs_revision', 'نیازمند اصلاح'), ('published', 'منتشر شده'), ('suspended', 'تعلیق شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'عرضه',
                'verbose_name_plural': 'عرضه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.supply_image_path, verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان تصویر')),
                ('is_primary', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
            ],
            options={
                'verbose_name': 'تصویر عرضه',
                'verbose_name_plural': 'تصاویر عرضه',
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('category', models.CharField(choices=[('product', 'محصول'), ('service', 'خدمت')], default='product', max_length=20, verbose_name='نوع')),
                ('short_description', models.TextField(verbose_name='توضیح کوتاه')),
                ('full_description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیح کامل')),
                ('problem_solved', models.TextField(blank=True, null=True, verbose_name='مسئله حل شده')),
                ('competitive_advantage', models.TextField(blank=True, null=True, verbose_name='مزیت رقابتی')),
                ('technical_specs', models.TextField(blank=True, null=True, verbose_name='مشخصات فنی')),
                ('trl', models.IntegerField(choices=[(1, 'TRL 1'), (2, 'TRL 2'), (3, 'TRL 3'), (4, 'TRL 4'), (5, 'TRL 5'), (6, 'TRL 6'), (7, 'TRL 7'), (8, 'TRL 8'), (9, 'TRL 9')], default=1, verbose_name='سطح آمادگی فناوری')),
                ('mrl', models.IntegerField(choices=[(1, 'MRL 1'), (2, 'MRL 2'), (3, 'MRL 3'), (4, 'MRL 4'), (5, 'MRL 5'), (6, 'MRL 6'), (7, 'MRL 7'), (8, 'MRL 8'), (9, 'MRL 9')], default=1, verbose_name='سطح آمادگی بازار')),
                ('pricing_model', models.TextField(blank=True, null=True, verbose_name='مدل قیمت\u200cگذاری')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='قیمت (تومان)')),
                ('ip_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='وضعیت مالکیت فکری')),
                ('documentation', models.FileField(blank=True, null=True, upload_to='products/docs/', verbose_name='مستندات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name='تصویر')),
                ('video', models.URLField(blank=True, null=True, verbose_name='ویدیو معرفی')),
                ('certificates', models.FileField(blank=True, null=True, upload_to='products/certs/', verbose_name='گواهی\u200cها')),
                ('sample_customers', models.TextField(blank=True, null=True, verbose_name='نمونه مشتریان')),
                ('capacity', models.CharField(blank=True, max_length=100, null=True, verbose_name='ظرفیت ارائه')),
                ('collaboration_terms', models.TextField(blank=True, null=True, verbose_name='شرایط همکاری')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ارسال برای بررسی'), ('evaluating', 'در حال ارزیابی'), ('needs_revision', 'نیازمند اصلاح'), ('approved', 'تأیید شده'), ('published', 'منتشر شده'), ('suspended', 'تعلیق شده'), ('in_negotiation', 'در حال مذاکره'), ('contracted', 'دارای قرارداد'), ('executing', 'در حال اجرا'), ('completed', 'تکمیل شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('view_count', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='industries.industrycategory', verbose_name='صنعت')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
