# Generated by Django 5.0 on 2026-08-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supply",
            name="view_count",
            field=models.IntegerField(default=0, verbose_name="تعداد بازدید"),
        ),
    ]
