# Generated by Django 5.0 on 2026-08-16 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplyimage",
            options={
                "ordering": ["-is_primary", "uploaded_at"],
                "verbose_name": "تصویر عرضه",
                "verbose_name_plural": "تصاویر عرضه",
            },
        ),
        migrations.AddField(
            model_name="supply",
            name="supply_type",
            field=models.CharField(
                choices=[("product", "محصول"), ("service", "خدمت")],
                default="product",
                max_length=20,
                verbose_name="نوع عرضه",
            ),
        ),
        migrations.AddField(
            model_name="supplyimage",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="تصویر اصلی"),
        ),
        migrations.AlterField(
            model_name="supply",
            name="category",
            field=models.CharField(max_length=100, verbose_name="دسته\u200cبندی"),
        ),
        migrations.AlterField(
            model_name="supply",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="شهر"),
        ),
        migrations.AlterField(
            model_name="supply",
            name="description",
            field=models.TextField(verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="supply",
            name="documents",
            field=models.JSONField(blank=True, default=list, verbose_name="مستندات"),
        ),
        migrations.AlterField(
            model_name="supply",
            name="industry",
            field=models.CharField(blank=True, max_length=100, verbose_name="صنعت"),
        ),
        migrations.AlterField(
            model_name="supply",
            name="quantity",
            field=models.CharField(max_length=50, verbose_name="مقدار"),
        ),
        migrations.AlterField(
            model_name="supply",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="فروشنده",
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار بررسی"),
                    ("approved", "تأیید شده"),
                    ("rejected", "رد شده"),
                    ("draft", "پیش\u200cنویس"),
                    ("submitted", "ارسال برای بررسی"),
                    ("evaluating", "در حال ارزیابی"),
                    ("needs_revision", "نیازمند اصلاح"),
                    ("published", "منتشر شده"),
                    ("suspended", "تعلیق شده"),
                ],
                default="pending",
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="technology",
            field=models.CharField(blank=True, max_length=100, verbose_name="فناوری"),
        ),
        migrations.AlterField(
            model_name="supply",
            name="title",
            field=models.CharField(max_length=200, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="supply",
            name="trl",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="سطح آمادگی فناوری"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="unit",
            field=models.CharField(max_length=50, verbose_name="واحد"),
        ),
        migrations.AlterField(
            model_name="supplyimage",
            name="caption",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="عنوان تصویر"
            ),
        ),
        migrations.AlterField(
            model_name="supplyimage",
            name="supply",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.supply",
                verbose_name="عرضه",
            ),
        ),
        migrations.AlterField(
            model_name="supplyimage",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ آپلود"),
        ),
    ]
