# Generated by Django 5.0 on 2026-09-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_favorite_favorite_unique_user_product_favorite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supply",
            name="mrl",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="سطح آمادگی تولید (MRL)"
            ),
        ),
        migrations.AddField(
            model_name="supply",
            name="mrl_assessed",
            field=models.BooleanField(
                default=False, verbose_name="MRL تأیید شده با ارزیابی"
            ),
        ),
        migrations.AddField(
            model_name="supply",
            name="trl_assessed",
            field=models.BooleanField(
                default=False, verbose_name="TRL تأیید شده با ارزیابی"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="trl",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="سطح آمادگی فناوری (TRL)"
            ),
        ),
    ]
