# Generated by Django 5.0 on 2026-07-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, null=True, verbose_name="یادداشت ارزیاب"
                    ),
                ),
                (
                    "quality_score",
                    models.IntegerField(default=0, verbose_name="امتیاز کیفیت"),
                ),
                (
                    "risk_score",
                    models.IntegerField(default=0, verbose_name="امتیاز ریسک"),
                ),
                (
                    "market_readiness_score",
                    models.IntegerField(default=0, verbose_name="امتیاز آمادگی بازار"),
                ),
                (
                    "final_decision",
                    models.CharField(
                        choices=[
                            ("approved", "تأیید برای انتشار"),
                            ("conditional", "تأیید مشروط"),
                            ("needs_info", "نیازمند تکمیل اطلاعات"),
                            ("rejected", "رد درخواست"),
                            ("referred", "ارجاع به ارزیاب تخصصی"),
                        ],
                        default="needs_info",
                        max_length=20,
                        verbose_name="تصمیم نهایی",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "ارزیابی",
                "verbose_name_plural": "ارزیابی\u200cها",
            },
        ),
    ]
