# Generated by Django 5.0 on 2026-07-27 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("industries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام شاخص")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("conversion", "نرخ تبدیل"),
                            ("retention", "ماندگاری"),
                            ("revenue", "درآمد"),
                            ("satisfaction", "رضایت"),
                            ("matching", "موفقیت تطبیق"),
                        ],
                        max_length=20,
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
                ("value", models.FloatField(verbose_name="مقدار")),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "شاخص کلیدی",
                "verbose_name_plural": "شاخص\u200cهای کلیدی",
            },
        ),
        migrations.CreateModel(
            name="MarketTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trend_name",
                    models.CharField(max_length=200, verbose_name="نام روند"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "data_points",
                    models.JSONField(default=list, verbose_name="نقاط داده"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "industry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="industries.industrycategory",
                        verbose_name="صنعت",
                    ),
                ),
            ],
            options={
                "verbose_name": "روند بازار",
                "verbose_name_plural": "روندهای بازار",
            },
        ),
    ]
