# Generated by Django 5.0 on 2026-07-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loyalty_points",
                    models.IntegerField(default=0, verbose_name="امتیاز وفاداری"),
                ),
                (
                    "total_purchases",
                    models.IntegerField(default=0, verbose_name="تعداد خریدها"),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, verbose_name="برچسب\u200cها"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="یادداشت\u200cها"
                    ),
                ),
                (
                    "last_contact",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین تماس"
                    ),
                ),
            ],
            options={
                "verbose_name": "پروفایل مشتری",
                "verbose_name_plural": "پروفایل\u200cهای مشتریان",
            },
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("call", "تماس"),
                            ("email", "ایمیل"),
                            ("meeting", "جلسه"),
                            ("note", "یادداشت"),
                        ],
                        max_length=20,
                        verbose_name="نوع تعامل",
                    ),
                ),
                ("details", models.TextField(verbose_name="جزئیات")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "تعامل",
                "verbose_name_plural": "تعاملات",
            },
        ),
    ]
