# Generated by Django 5.0 on 2026-08-21 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام صنعت')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='کلیدواژه\u200cها')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='industries/icons/', verbose_name='آیکون')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='industries.industrycategory', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته صنعت',
                'verbose_name_plural': 'دسته\u200cهای صنعت',
            },
        ),
    ]
