# Generated by Django 5.0 on 2026-08-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='کلید')),
                ('value', models.TextField(verbose_name='مقدار')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات پلتفرم',
                'verbose_name_plural': 'تنظیمات پلتفرم',
            },
        ),
        migrations.CreateModel(
            name='QualityControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(max_length=50, verbose_name='نوع هدف')),
                ('target_id', models.PositiveIntegerField(verbose_name='شناسه هدف')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('passed', 'تأیید شده'), ('failed', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کنترل کیفیت',
                'verbose_name_plural': 'کنترل کیفیت',
            },
        ),
    ]
