# Generated by Django 5.0 on 2026-08-21 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'ایجاد شده'), ('in_progress', 'در حال مکاتبه'), ('awaiting_proposal', 'در انتظار پیشنهاد'), ('proposal_sent', 'پیشنهاد ارسال شده'), ('under_review', 'در حال بررسی'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده'), ('contracted', 'ورود به قرارداد')], default='created', max_length=20)),
                ('context_meta', models.JSONField(default=dict)),
                ('context_title', models.CharField(blank=True, max_length=255, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, null=True, upload_to='negotiation_files/%Y/%m/')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='negotiations.message')),
            ],
            options={
                'db_table': 'negotiations_negotiationmessage',
                'ordering': ['timestamp', 'id'],
            },
        ),
    ]
