# Generated by Django 5.0 on 2026-07-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="متن پیام")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="negotiations/files/",
                        verbose_name="فایل ضمیمه",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "پیام",
                "verbose_name_plural": "پیام\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Negotiation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "ایجاد شده"),
                            ("in_progress", "در حال مکاتبه"),
                            ("awaiting_proposal", "در انتظار پیشنهاد"),
                            ("proposal_sent", "پیشنهاد ارسال شده"),
                            ("under_review", "در حال بررسی"),
                            ("accepted", "پذیرفته شده"),
                            ("rejected", "رد شده"),
                            ("contracted", "ورود به قرارداد"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "مذاکره",
                "verbose_name_plural": "مذاکرات",
            },
        ),
    ]
