# Generated by Django 6.0.6 on 2026-08-16 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negotiations", "0001_initial"),
        ("products", "0003_alter_supplyimage_options_supply_supply_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["timestamp", "id"]},
        ),
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="negotiation_files/%Y/%m/"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="negotiation_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="negotiation",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="negotiations",
                to="products.product",
            ),
        ),
    ]
