# Generated by Django 5.0 on 2026-08-21 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negotiations', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations_as_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations_as_supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='products.supply'),
        ),
        migrations.AddField(
            model_name='message',
            name='negotiation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='negotiations.negotiation'),
        ),
    ]
