# Generated by Django 5.0 on 2026-08-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("negotiations", "0002_alter_message_options_message_file_and_more"),
        ("negotiations", "0002_reconcile_existing_schema"),
    ]

    operations = []
