# Generated by Django 5.0 on 2026-08-10 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("needs", "0002_initial"),
        ("negotiations", "0002_initial"),
        ("products", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "پیام",
                "verbose_name_plural": "پیام\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="negotiation",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "مذاکره",
                "verbose_name_plural": "مذاکرات",
            },
        ),
        migrations.AlterField(
            model_name="message",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="messages/%Y/%m/%d/",
                verbose_name="فایل پیوست",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="negotiation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="negotiations.negotiation",
                verbose_name="مذاکره",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="negotiation_sent_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="فرستنده",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="زمان ارسال"),
        ),
        migrations.AlterField(
            model_name="negotiation",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyer_negotiations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="خریدار",
            ),
        ),
        migrations.AlterField(
            model_name="negotiation",
            name="need",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="negotiations",
                to="needs.need",
                verbose_name="نیاز",
            ),
        ),
        migrations.AlterField(
            model_name="negotiation",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="negotiations",
                to="products.product",
                verbose_name="محصول",
            ),
        ),
        migrations.AlterField(
            model_name="negotiation",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_negotiations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تأمین\u200cکننده",
            ),
        ),
    ]
