# Generated by Django 5.0 on 2026-08-19 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("negotiations", "0003_merge_20260817_1605"),
    ]

    operations = [
      
    ]
