# Generated by Django 5.0 on 2026-07-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MatchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0.0, verbose_name="درصد انطباق")),
                (
                    "reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="دلیل پیشنهاد"
                    ),
                ),
                (
                    "recommended_actions",
                    models.TextField(
                        blank=True, null=True, verbose_name="اقدامات پیشنهادی"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "نتیجه تطبیق",
                "verbose_name_plural": "نتایج تطبیق",
            },
        ),
    ]
