# Generated by Django 5.0 on 2026-08-21 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        ('needs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingrequest',
            name='need',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_requests', to='needs.need', verbose_name='نیاز'),
        ),
    ]
