# Generated by Django 5.0 on 2026-07-27 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matching", "0001_initial"),
        ("needs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchresult",
            name="need",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="needs.need",
            ),
        ),
    ]
