# Generated by Django 5.0 on 2026-08-21 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0002_initial'),
        ('needs', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر درخواست\u200cکننده'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='need',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='needs.need', verbose_name='نیاز'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterUniqueTogether(
            name='matchresult',
            unique_together={('need', 'product')},
        ),
    ]
