# Generated by Django 5.0 on 2026-08-31 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0003_initial"),
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchresult",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_results",
                to="products.supply",
                verbose_name="عرضه",
            ),
        ),
    ]
