# Generated by Django 5.0 on 2026-08-19 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0003_initial"),
        ("needs", "0002_initial"),
        ("products", "0003_alter_supplyimage_options_supply_supply_type_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="matchresult",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="matchresult",
            name="supply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_results",
                to="products.supply",
                verbose_name="عرضه",
            ),
        ),
        migrations.AlterField(
            model_name="matchresult",
            name="need",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="needs.need",
                verbose_name="نیاز",
            ),
        ),
        migrations.AlterField(
            model_name="matchresult",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="products.product",
                verbose_name="محصول",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchresult",
            constraint=models.UniqueConstraint(
                condition=models.Q(("product__isnull", False)),
                fields=("need", "product"),
                name="unique_need_product_match",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchresult",
            constraint=models.UniqueConstraint(
                condition=models.Q(("supply__isnull", False)),
                fields=("need", "supply"),
                name="unique_need_supply_match",
            ),
        ),
    ]
