# Generated by Django 5.0 on 2026-07-27 11:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Need",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان نیاز")),
                (
                    "description",
                    ckeditor.fields.RichTextField(verbose_name="شرح مسئله"),
                ),
                (
                    "current_status",
                    models.TextField(blank=True, null=True, verbose_name="وضعیت فعلی"),
                ),
                (
                    "expected_outcome",
                    models.TextField(
                        blank=True, null=True, verbose_name="خروجی مورد انتظار"
                    ),
                ),
                (
                    "constraints",
                    models.TextField(
                        blank=True, null=True, verbose_name="محدودیت\u200cها"
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="بودجه (تومان)",
                    ),
                ),
                (
                    "timeline",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="زمان\u200cبندی",
                    ),
                ),
                (
                    "confidentiality",
                    models.CharField(
                        choices=[("public", "عمومی"), ("private", "خصوصی")],
                        default="public",
                        max_length=20,
                        verbose_name="سطح محرمانگی",
                    ),
                ),
                (
                    "evaluation_criteria",
                    models.TextField(
                        blank=True, null=True, verbose_name="معیارهای ارزیابی"
                    ),
                ),
                (
                    "attachments",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="needs/attachments/",
                        verbose_name="فایل\u200cهای پیوست",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("published", "منتشر شده"),
                            ("private", "خصوصی"),
                            ("receiving_proposals", "در حال دریافت پیشنهاد"),
                            ("evaluating", "در حال ارزیابی"),
                            ("matched", "تطبیق داده شده"),
                            ("in_negotiation", "در حال مذاکره"),
                            ("contracted", "تبدیل به قرارداد"),
                            ("executing", "در حال اجرا"),
                            ("closed", "بسته شده"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "نیاز",
                "verbose_name_plural": "نیازها",
            },
        ),
    ]
