# Generated by Django 6.0.6 on 2026-09-01 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industries", "0001_initial"),
        ("needs", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="need",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "نیاز",
                "verbose_name_plural": "نیازها",
            },
        ),
        migrations.AlterField(
            model_name="need",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="needs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ثبت\u200cکننده",
            ),
        ),
        migrations.AlterField(
            model_name="need",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="need",
            name="industry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="industries.industrycategory",
                verbose_name="صنعت",
            ),
        ),
        migrations.AlterField(
            model_name="need",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
        ),
    ]
