# Generated by Django 5.0 on 2026-07-27 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketReadiness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "market_readiness_score",
                    models.FloatField(default=0.0, verbose_name="امتیاز آمادگی بازار"),
                ),
                (
                    "market_fit_score",
                    models.FloatField(default=0.0, verbose_name="امتیاز تطابق بازار"),
                ),
                (
                    "demand_forecast",
                    models.JSONField(default=dict, verbose_name="پیش\u200cبینی تقاضا"),
                ),
                (
                    "competitive_position",
                    models.TextField(
                        blank=True, null=True, verbose_name="موقعیت رقابتی"
                    ),
                ),
                (
                    "recommended_actions",
                    models.TextField(
                        blank=True, null=True, verbose_name="پیشنهاد اصلاح"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readiness",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "سنجش بازارپذیری",
                "verbose_name_plural": "سنجش بازارپذیری",
            },
        ),
    ]
