# Generated by Django 5.0 on 2026-07-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="موضوع")),
                ("description", models.TextField(verbose_name="شرح")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جدید"),
                            ("in_progress", "در حال بررسی"),
                            ("answered", "پاسخ داده شده"),
                            ("referred", "ارجاع شده"),
                            ("needs_seller_action", "نیازمند اقدام فروشنده"),
                            ("closed", "بسته شده"),
                            ("disputed", "وارد داوری شده"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "کم"), ("medium", "متوسط"), ("high", "زیاد")],
                        default="medium",
                        max_length=10,
                        verbose_name="اولویت",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "تیکت",
                "verbose_name_plural": "تیکت\u200cها",
            },
        ),
        migrations.CreateModel(
            name="TicketMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="متن")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="tickets/files/",
                        verbose_name="فایل ضمیمه",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "پیام تیکت",
                "verbose_name_plural": "پیام\u200cهای تیکت",
            },
        ),
    ]
