# Generated by Django 5.0 on 2026-07-27 11:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("buyer", "خریدار محصول فناورانه"),
                            ("buyer_service", "خریدار خدمت نوآورانه"),
                            ("supplier", "عرضه\u200cکننده محصول"),
                            ("supplier_service", "عرضه\u200cکننده خدمت"),
                            ("need_registerer", "ثبت\u200cکننده نیاز فناورانه"),
                            ("investor", "سرمایه\u200cگذار"),
                            ("consultant", "مشاور / ارزیاب"),
                            ("broker", "کارگزار / کارشناس رسمی"),
                            ("partner", "سازمان همکار"),
                            ("admin", "مدیر پلتفرم"),
                        ],
                        default="buyer",
                        max_length=20,
                    ),
                ),
                ("is_legal", models.BooleanField(default=False)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("national_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "economic_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "representative_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("expertise", models.TextField(blank=True, null=True)),
                ("activity_domain", models.TextField(blank=True, null=True)),
                ("experience_summary", models.TextField(blank=True, null=True)),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("pending", "در انتظار بررسی"),
                            ("approved", "تأیید شده"),
                            ("rejected", "رد شده"),
                            ("suspended", "تعلیق شده"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
