# Generated by Django 6.0.6 on 2026-08-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار تأیید"),
                    ("approved", "تأیید شده"),
                    ("rejected", "رد شده"),
                ],
                default="pending",
                max_length=20,
                verbose_name="وضعیت تأیید ثبت\u200cنام",
            ),
        ),
    ]
