# Generated by Django 5.0 on 2026-08-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_card', 'کارت ملی'), ('registration', 'اسناد ثبتی'), ('license', 'مجوز یا پروانه'), ('representative', 'معرفی\u200cنامه نماینده'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع مدرک')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('file', models.FileField(upload_to='documents/', verbose_name='فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False, verbose_name='تأیید شده')),
            ],
            options={
                'verbose_name': 'مستند کاربر',
                'verbose_name_plural': 'مستندات کاربران',
            },
        ),
    ]
